import io
import json
import re
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import streamlit as st

BASE = Path(__file__).resolve().parent
MODEL_PATH = BASE / "sgc_model.joblib"
META_PATH = BASE / "sgc_model_metadata.json"

st.set_page_config(page_title="Secondary Genetic Code Explorer", page_icon="🧬", layout="wide")

@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)

@st.cache_data
def load_metadata():
    with open(META_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

model = load_model()
meta = load_metadata()
POS_COLS = [f"pos_{i}" for i in range(1, 86)]


def clean_sequence(seq: str) -> str:
    seq = re.sub(r"[^A-Za-z]", "", str(seq)).upper().replace("U", "T")
    return seq


def sequence_to_features(seq: str) -> pd.DataFrame:
    seq = clean_sequence(seq)
    vals = [seq[i] if i < len(seq) else "MISSING" for i in range(85)]
    row = {c: v for c, v in zip(POS_COLS, vals)}
    row["length"] = len(seq)
    return pd.DataFrame([row])


def predict_sequence(seq: str):
    X = sequence_to_features(seq)
    pred = model.predict(X)[0]
    probs = model.predict_proba(X)[0]
    classes = model.classes_
    order = np.argsort(probs)[::-1]
    ranked = pd.DataFrame({"Amino acid": classes[order], "Probability": probs[order]})
    return pred, ranked


def parse_fasta(text: str):
    records = []
    name = None
    chunks = []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.startswith(">"):
            if name is not None:
                records.append((name, "".join(chunks)))
            name = line[1:].strip() or f"sequence_{len(records)+1}"
            chunks = []
        else:
            chunks.append(line)
    if name is not None:
        records.append((name, "".join(chunks)))
    return records


def position_summary(seq: str):
    seq = clean_sequence(seq)
    def base(pos):
        return seq[pos-1] if len(seq) >= pos else "—"
    anticodon = seq[33:36] if len(seq) >= 36 else "—"
    return {
        "Length": len(seq),
        "Position 3": base(3),
        "Anticodon region (34–36)": anticodon,
        "Position 70": base(70),
        "Position 72": base(72),
        "Position 73": base(73),
        "G3:T70 motif": "Present" if len(seq) >= 70 and base(3)=="G" and base(70)=="T" else "Not present",
    }

st.title("🧬 Secondary Genetic Code Explorer")
st.caption("A scientist-facing prototype derived from a Ph.D. tRNA sequence dataset: 20 amino-acid classes, nucleotide positions 1–85, and six species.")
st.info("Research prototype: predictions are generated by a class-balanced logistic-regression baseline trained on the supplied dissertation dataset. They are for exploration, not experimental or clinical decision-making.")

m1,m2,m3,m4=st.columns(4)
m1.metric("Original rows", f"{meta['n_original_rows']:,}")
m2.metric("Unique training rows", f"{meta['n_training_rows_after_exact_dedup']:,}")
m3.metric("Grouped holdout accuracy", f"{meta['grouped_holdout_accuracy']:.1%}")
m4.metric("Macro-F1", f"{meta['grouped_holdout_macro_f1']:.1%}")

tab1, tab2, tab3, tab4 = st.tabs(["Single sequence", "Batch analysis", "Model insights", "About / limitations"])

with tab1:
    st.subheader("Analyze one tRNA sequence")
    default = "GCGTTGGTGGTATAGTGGTGAGCATAGCTGCCTAAGCAGTTGACCCGGGTTCGATTCCCGGCCAACGCA"
    seq = st.text_area("Paste DNA or RNA sequence", value=default, height=120, help="U is converted to T. Non-letter characters are removed.")
    cleaned = clean_sequence(seq)
    if cleaned:
        invalid = sorted(set(cleaned) - set("ACGTN"))
        if invalid:
            st.error(f"Unsupported characters after cleaning: {invalid}")
        elif len(cleaned) > 85:
            st.warning("The training table contains positions 1–85. Only the first 85 positions are represented by the model, while length is retained as a feature.")
        if st.button("Predict amino-acid identity", type="primary"):
            pred, ranked = predict_sequence(cleaned)
            left,right = st.columns([1,2])
            with left:
                st.metric("Predicted class", pred)
                top_prob=float(ranked.iloc[0]["Probability"])
                st.metric("Top-class probability", f"{top_prob:.1%}")
                st.write("**Sequence features**")
                st.dataframe(pd.DataFrame(position_summary(cleaned).items(), columns=["Feature","Value"]), hide_index=True, use_container_width=True)
            with right:
                st.write("**Top predictions**")
                top = ranked.head(8).copy()
                top["Probability"] = top["Probability"].map(lambda x: f"{x:.2%}")
                st.dataframe(top, hide_index=True, use_container_width=True)
                st.bar_chart(ranked.head(10).set_index("Amino acid")["Probability"])

with tab2:
    st.subheader("Batch prediction")
    st.write("Upload a FASTA file, or a CSV/TSV containing a column named `sequence`. Optional identifier columns are preserved.")
    up = st.file_uploader("Upload batch sequences", type=["fasta","fa","fas","csv","tsv","txt"])
    if up:
        name=up.name.lower()
        if name.endswith((".fasta",".fa",".fas",".txt")):
            text=up.getvalue().decode("utf-8", errors="replace")
            records=parse_fasta(text)
            batch=pd.DataFrame(records, columns=["id","sequence"])
        else:
            sep="\t" if name.endswith(".tsv") else ","
            batch=pd.read_csv(up, sep=sep)
            if "sequence" not in batch.columns:
                st.error("The table must contain a `sequence` column.")
                st.stop()
        if len(batch):
            results=[]
            for _,row in batch.iterrows():
                seqv=clean_sequence(row["sequence"])
                if not seqv:
                    pred=""; conf=np.nan
                else:
                    p, ranked=predict_sequence(seqv); pred=p; conf=float(ranked.iloc[0]["Probability"])
                rec=row.to_dict(); rec.update({"clean_sequence":seqv,"length":len(seqv),"predicted_amino_acid":pred,"top_probability":conf})
                results.append(rec)
            result=pd.DataFrame(results)
            st.success(f"Processed {len(result):,} sequences")
            st.dataframe(result.head(200), use_container_width=True)
            st.download_button("Download predictions CSV", result.to_csv(index=False).encode("utf-8"), "sgc_predictions.csv", "text/csv")

with tab3:
    st.subheader("Model design and validation")
    st.write("**Baseline:** one-hot encoded nucleotide identities at positions 1–85 plus sequence length, followed by class-balanced logistic regression.")
    st.write("**Leakage control:** exact duplicate sequence/class rows were removed before training, and evaluation used a 20% GroupShuffleSplit grouped by exact sequence. Identical sequences therefore cannot occur in both training and test sets.")
    st.write(f"**Grouped holdout:** {meta['grouped_holdout_accuracy']:.3f} accuracy; {meta['grouped_holdout_macro_f1']:.3f} macro-F1 on {meta['test_rows']:,} held-out rows.")
    st.write("**Classes:** " + ", ".join(meta["classes"]))
    st.write("**Species:** " + ", ".join(meta["species"]))
    st.code("sequence → standardized positions → one-hot encoding → logistic regression → class probabilities → scientist-facing output", language="text")
    st.warning("A stronger biological generalization test would hold out entire species or evolutionary groups. The included Colab notebook shows how to extend validation rather than treating this baseline as final biological evidence.")

with tab4:
    st.subheader("What this app demonstrates")
    st.markdown("""
- Translation of a scientific sequence-analysis workflow into a reusable user-facing model.
- Standardized inputs, deterministic preprocessing, documented assumptions, reproducible prediction, and downloadable outputs.
- Explicit separation of training/validation from deployment.
- A simple, interpretable baseline before adding more complex models.
""")
    st.subheader("Limitations")
    st.markdown("""
- Positions are treated as sequential columns from the supplied dataset; the app does not infer canonical tRNA structural numbering or perform sequence alignment.
- The data contain repeated sequences and uneven class/species distributions; grouped validation reduces duplicate leakage but does not eliminate all sources of dataset bias.
- Prediction confidence is model probability, not biological certainty.
- This prototype should not be presented as a validated production or clinical model.
""")
